name = "rxventure-dungeon"
pages_build_output_dir = "dist"
compatibility_date = "2026-09-24"
[vars]
VITE_SUPABASE_URL = "https://hvmfekipwhvjhyqbboxc.supabase.co"
SUPABASE_URL = "https://hvmfekipwhvjhyqbboxc.supabase.co"
